version: '3'
services:
  client:
    container_name: debug_dev_client
    build: ./client
    image: debug_client
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
volumes:
  dbdata:
networks:
  default:
    name: debug_api
